micronaut:
  application:
    name: justserve-cli
    version: "@justserveCliVersion@"
  http:
    services:
      justserve:
        url: https://www.justserve.org
justserve:
  token: ${:i-need-to-be-defined}
logger:
  levels:
#    org.justserve.auth.JustServeClientFilter: DEBUG