package org.justserve.model;

import lombok.Getter;

@Getter
public enum TimeZone {
    INTERNATIONAL_DATE_LINE_WEST("(UTC-12:00) International Date Line West"),
    COORDINATED_UNIVERSAL_TIME_11("(UTC-11:00) Coordinated Universal Time-11"),
    ALEUTIAN_ISLANDS("(UTC-10:00) Aleutian Islands"),
    HAWAII("(UTC-10:00) Hawaii"),
    MARQUESAS_ISLANDS("(UTC-09:30) Marquesas Islands"),
    ALASKA("(UTC-09:00) Alaska"),
    COORDINATED_UNIVERSAL_TIME_09("(UTC-09:00) Coordinated Universal Time-09"),
    BAJA_CALIFORNIA("(UTC-08:00) Baja California"),
    COORDINATED_UNIVERSAL_TIME_08("(UTC-08:00) Coordinated Universal Time-08"),
    PACIFIC_TIME_US_AND_CANADA("(UTC-08:00) Pacific Time (US & Canada)"),
    ARIZONA("(UTC-07:00) Arizona"),
    LA_PAZ("(UTC-07:00) La Paz"),
    MOUNTAIN_TIME_US_AND_CANADA("(UTC-07:00) Mountain Time (US & Canada)"),
    YUKON("(UTC-07:00) Yukon"),
    CENTRAL_AMERICA("(UTC-06:00) Central America"),
    CENTRAL_TIME_US_AND_CANADA("(UTC-06:00) Central Time (US & Canada)"),
    EASTER_ISLAND("(UTC-06:00) Easter Island"),
    GUADALAJARA("(UTC-06:00) Guadalajara"),
    SASKATCHEWAN("(UTC-06:00) Saskatchewan"),
    BOGOTA("(UTC-05:00) Bogota"),
    CHETUMAL("(UTC-05:00) Chetumal"),
    EASTERN_TIME_US_AND_CANADA("(UTC-05:00) Eastern Time (US & Canada)"),
    HAITI("(UTC-05:00) Haiti"),
    HAVANA("(UTC-05:00) Havana"),
    INDIANA_EAST("(UTC-05:00) Indiana (East)"),
    TURKS_AND_CAICOS("(UTC-05:00) Turks and Caicos"),
    ASUNCION("(UTC-04:00) Asuncion"),
    ATLANTIC_TIME_CANADA("(UTC-04:00) Atlantic Time (Canada)"),
    CARACAS("(UTC-04:00) Caracas"),
    CUIABA("(UTC-04:00) Cuiaba"),
    GEORGETOWN("(UTC-04:00) Georgetown"),
    SANTIAGO("(UTC-04:00) Santiago"),
    NEWFOUNDLAND("(UTC-03:30) Newfoundland"),
    ARAGUAINA("(UTC-03:00) Araguaina"),
    BRASILIA("(UTC-03:00) Brasilia"),
    CAYENNE("(UTC-03:00) Cayenne"),
    CITY_OF_BUENOS_AIRES("(UTC-03:00) City of Buenos Aires"),
    MONTEVIDEO("(UTC-03:00) Montevideo"),
    PUNTA_ARENAS("(UTC-03:00) Punta Arenas"),
    SAINT_PIERRE_AND_MIQUELON("(UTC-03:00) Saint Pierre and Miquelon"),
    SALVADOR("(UTC-03:00) Salvador"),
    COORDINATED_UNIVERSAL_TIME_02("(UTC-02:00) Coordinated Universal Time-02"),
    GREENLAND("(UTC-02:00) Greenland"),
    MID_ATLANTIC_OLD("(UTC-02:00) Mid-Atlantic - Old"),
    AZORES("(UTC-01:00) Azores"),
    CABO_VERDE_IS("(UTC-01:00) Cabo Verde Is."),
    COORDINATED_UNIVERSAL_TIME("(UTC) Coordinated Universal Time"),
    DUBLIN("(UTC+00:00) Dublin"),
    MONROVIA("(UTC+00:00) Monrovia"),
    SAO_TOME("(UTC+00:00) Sao Tome"),
    CASABLANCA("(UTC+01:00) Casablanca"),
    AMSTERDAM("(UTC+01:00) Amsterdam"),
    BELGRADE("(UTC+01:00) Belgrade"),
    BRUSSELS("(UTC+01:00) Brussels"),
    SARAJEVO("(UTC+01:00) Sarajevo"),
    WEST_CENTRAL_AFRICA("(UTC+01:00) West Central Africa"),
    ATHENS("(UTC+02:00) Athens"),
    BEIRUT("(UTC+02:00) Beirut"),
    CAIRO("(UTC+02:00) Cairo"),
    CHISINAU("(UTC+02:00) Chisinau"),
    GAZA("(UTC+02:00) Gaza"),
    HARARE("(UTC+02:00) Harare"),
    HELSINKI("(UTC+02:00) Helsinki"),
    JERUSALEM("(UTC+02:00) Jerusalem"),
    JUBA("(UTC+02:00) Juba"),
    KALININGRAD("(UTC+02:00) Kaliningrad"),
    KHARTOUM("(UTC+02:00) Khartoum"),
    TRIPOLI("(UTC+02:00) Tripoli"),
    WINDHOEK("(UTC+02:00) Windhoek"),
    AMMAN("(UTC+03:00) Amman"),
    BAGHDAD("(UTC+03:00) Baghdad"),
    DAMASCUS("(UTC+03:00) Damascus"),
    ISTANBUL("(UTC+03:00) Istanbul"),
    KUWAIT("(UTC+03:00) Kuwait"),
    MINSK("(UTC+03:00) Minsk"),
    MOSCOW("(UTC+03:00) Moscow"),
    NAIROBI("(UTC+03:00) Nairobi"),
    VOLGOGRAD("(UTC+03:00) Volgograd"),
    TEHRAN("(UTC+03:30) Tehran"),
    ABU_DHABI("(UTC+04:00) Abu Dhabi"),
    ASTRAKHAN("(UTC+04:00) Astrakhan"),
    BAKU("(UTC+04:00) Baku"),
    IZHEVSK("(UTC+04:00) Izhevsk"),
    PORT_LOUIS("(UTC+04:00) Port Louis"),
    SARATOV("(UTC+04:00) Saratov"),
    TBILISI("(UTC+04:00) Tbilisi"),
    YEREVAN("(UTC+04:00) Yerevan"),
    KABUL("(UTC+04:30) Kabul"),
    ASHGABAT("(UTC+05:00) Ashgabat"),
    ASTANA("(UTC+05:00) Astana"),
    EKATERINBURG("(UTC+05:00) Ekaterinburg"),
    ISLAMABAD("(UTC+05:00) Islamabad"),
    CHENNAI("(UTC+05:30) Chennai"),
    SRI_JAYAWARDENEPURA("(UTC+05:30) Sri Jayawardenepura"),
    KATHMANDU("(UTC+05:45) Kathmandu"),
    BISHKEK("(UTC+06:00) Bishkek"),
    DHAKA("(UTC+06:00) Dhaka"),
    OMSK("(UTC+06:00) Omsk"),
    YANGON_RANGOON("(UTC+06:30) Yangon (Rangoon)"),
    BANGKOK("(UTC+07:00) Bangkok"),
    BARNAUL("(UTC+07:00) Barnaul"),
    HOVD("(UTC+07:00) Hovd"),
    KRASNOYARSK("(UTC+07:00) Krasnoyarsk"),
    NOVOSIBIRSK("(UTC+07:00) Novosibirsk"),
    TOMSK("(UTC+07:00) Tomsk"),
    BEIJING("(UTC+08:00) Beijing"),
    IRKUTSK("(UTC+08:00) Irkutsk"),
    KUALA_LUMPUR("(UTC+08:00) Kuala Lumpur"),
    PERTH("(UTC+08:00) Perth"),
    TAIPEI("(UTC+08:00) Taipei"),
    ULAANBAATAR("(UTC+08:00) Ulaanbaatar"),
    EUCLA("(UTC+08:45) Eucla"),
    CHITA("(UTC+09:00) Chita"),
    OSAKA("(UTC+09:00) Osaka"),
    PYONGYANG("(UTC+09:00) Pyongyang"),
    SEOUL("(UTC+09:00) Seoul"),
    YAKUTSK("(UTC+09:00) Yakutsk"),
    ADELAIDE("(UTC+09:30) Adelaide"),
    DARWIN("(UTC+09:30) Darwin"),
    BRISBANE("(UTC+10:00) Brisbane"),
    CANBERRA("(UTC+10:00) Canberra"),
    GUAM("(UTC+10:00) Guam"),
    HOBART("(UTC+10:00) Hobart"),
    VLADIVOSTOK("(UTC+10:00) Vladivostok"),
    LORD_HOWE_ISLAND("(UTC+10:30) Lord Howe Island"),
    BOUGAINVILLE_ISLAND("(UTC+11:00) Bougainville Island"),
    CHOKURDAKH("(UTC+11:00) Chokurdakh"),
    MAGADAN("(UTC+11:00) Magadan"),
    NORFOLK_ISLAND("(UTC+11:00) Norfolk Island"),
    SAKHALIN("(UTC+11:00) Sakhalin"),
    SOLOMON_IS("(UTC+11:00) Solomon Is."),
    ANADYR("(UTC+12:00) Anadyr"),
    AUCKLAND("(UTC+12:00) Auckland"),
    COORDINATED_UNIVERSAL_TIME_12("(UTC+12:00) Coordinated Universal Time+12"),
    FIJI("(UTC+12:00) Fiji"),
    PETROPAVLOVSK_KAMCHATSKY_OLD("(UTC+12:00) Petropavlovsk-Kamchatsky - Old"),
    CHATHAM_ISLANDS("(UTC+12:45) Chatham Islands"),
    COORDINATED_UNIVERSAL_TIME_13("(UTC+13:00) Coordinated Universal Time+13"),
    NUKU_ALOFA("(UTC+13:00) Nuku'alofa"),
    SAMOA("(UTC+13:00) Samoa"),
    KIRITIMATI_ISLAND("(UTC+14:00) Kiritimati Island");

    private final String displayName;

    TimeZone(String displayName) {
        this.displayName = displayName;
    }

}
