micronaut:
  application:
    name: justserve devkit core
  http:
    services:
      justserve:
        url: https://www.justserve.org
    client:
      read-timeout: 20s
justserve:
  token:
jackson:
  deserialization:
    ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
logger:
  levels:
#    org.justserve.auth.JustServeClientFilter: DEBUG