micronaut:
  application:
    name: justserve devkit core
  http:
    services:
      justserve:
        url: https://www.justserve.org
    client:
      read-timeout: 20s
      connect-timeout: 5s
      request-timeout: 30s
      retryAttempts: 3
      pool:
        enabled: true
        acquire-timeout: 30s
        max-connections: 100
justserve:
  token:
jackson:
  deserialization:
    ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
logger:
  levels:
#    org.justserve.auth.JustServeClientFilter: DEBUG