name: GraalVM Native Image Test run and build tests
on: [pull_request, workflow_dispatch]
jobs:
  build:
    name: test and compile on self-hosted
    runs-on: self-hosted
    env:
      TEST_TOKEN: ${{ secrets.MICRONAUT_HTTP_SERVICES_JUSTSERVE_TOKEN }}
      JAVA_HOME: ${{ secrets.JAVA_HOME }}

    steps:
      - uses: actions/checkout@v4
      - name: Run core tests
        run: ./gradlew :core:test
      - name: Run cli tests and compile
        run: ./gradlew :cli:test :cli:nativeCompile
      - name: upload binary
        uses: actions/upload-artifact@v4
        with:
          name: justserve
          path: cli/build/native/nativeCompile/justserve*